config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :categoria
    get "home" => "home#home"
    get "aula" => "aula#aula"
    get "login" => "login#login"
    get "upload" => "upload#upload"
    #root :to => "login#login"
    get 'sessions/new'
    resources :users
    get    'sign_in'   => 'sessions#new'
    post   'sign_in'   => 'sessions#create'
    delete 'sign_out'  => 'sessions#destroy'
     root 'sessions#new'
     
end

app/models/aula.rb
class Aula < ActiveRecord::Base

end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
end

app/models/login.rb
class Login < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base 
  has_secure_password
  #validates name, presence: true, length: {maximum: 50}
  #validates password, presence: true, length: {minimum: 6}
  #VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  #validates email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
  #before_save { self.email = email.downcase }
  end

app/models/video.rb
class Video < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/aula_controller.rb
class AulaController < ApplicationController

end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  before_action :set_categorium, only: [:show, :edit, :update, :destroy]

  # GET /categoria
  # GET /categoria.json
  def index
    @categoria = Categorium.all
  end

  # GET /categoria/1
  # GET /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @categorium = Categorium.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria
  # POST /categoria.json
  def create
    @categorium = Categorium.new(categorium_params)

    respond_to do |format|
      if @categorium.save
        format.html { redirect_to @categorium, notice: 'Categorium was successfully created.' }
        format.json { render :show, status: :created, location: @categorium }
      else
        format.html { render :new }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1
  # PATCH/PUT /categoria/1.json
  def update
    respond_to do |format|
      if @categorium.update(categorium_params)
        format.html { redirect_to @categorium, notice: 'Categorium was successfully updated.' }
        format.json { render :show, status: :ok, location: @categorium }
      else
        format.html { render :edit }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1
  # DELETE /categoria/1.json
  def destroy
    @categorium.destroy
    respond_to do |format|
      format.html { redirect_to categoria_url, notice: 'Categorium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorium
      @categorium = Categorium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categorium_params
      params.require(:categorium).permit(:nome)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
before_action :block_access, except: [:destroy]
         def create  
            @user = User.find_by(email: params[:session][:email].downcase)
                        if @user && @user.authenticate(params[:session][:password])
                                   sign_in(@user)
                                   redirect_to home_path
                        else
                                   render action: :new
                        end
            end
  
              def destroy
                        sign_out
                redirect_to root_url
              end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
            @user = User.new
  end
  def create
            @user = User.new(user_params)
            if @user.save
                        redirect_to home_path, notice: "Usuário foi criado com sucesso!"
                        #tire o método de comentário quando criar o helper.
                        #Usuário depois de cadastrar-se acessa o sistema automaticamente
                        sign_in(@user)
            else 
                render action: :new
            end
  end
  private
  def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aula_helper.rb
module AulaHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
            def sign_in(a)
                        session[:user_id] = @user.id
            end
            def current_user
                        @current_user ||= User.find_by(id: session[:user_id])
            end
            def block_access
                        if current_user.present?
                                   redirect_to home_path
                        end
            end
            def logged_in?
            !current_user.nil?
            end
               def sign_out
            session.delete(:user_id)
            @current_user = nil
            end

end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/aula/aula.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="css/index.css">
    <link rel="stylesheet" href="css/carousel.css">


    <title>Hello, world!</title>
  </head>
  <body>
    <div class="container">
    	<section class="video">
		 	<iframe width="100%" height="720" src="<%= $aula.url%>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
		</section>
		
		<hr>
		
		<section class="video-text">
			<p><%= $aula.descricao%></p>
		</section>
		
		<section class="form-box">
			<div class = 'text'>
				<div class="row">
					<div class="col-sm-6 col-sm-offset-3">
						<form id="todoForm">
							<div class="form-group">
								<input id="username" class="form-control" placeholder="Nome">
							</div>
							<div class="form-group">
								<textarea id="comment" class="form-control" placeholder="Participe da discussão..."></textarea>
							</div>
							<div class="form-group">
								<button type="button" onclick="todoList()" class="btn btn-style btn-lg">Enviar</button>
							</div>
						</form>
						<ul id="commentList" class="list-group"></ul>					
					</div>
				</div>
			</div>	
		</section>
    </div>
      
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="js/principal.js"></script>
    <script src="js/form.js"></script>
  </body>
</html>

app/views/categoria/_form.html.erb
<%= form_for(@categorium) do |f| %>
  <% if @categorium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categorium.errors.count, "error") %> prohibited this categorium from being saved:</h2>

      <ul>
      <% @categorium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categoria/edit.html.erb
<h1>Editing Categorium</h1>

<%= render 'form' %>

<%= link_to 'Show', @categorium %> |
<%= link_to 'Back', categoria_path %>

app/views/categoria/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categoria</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categoria.each do |categorium| %>
      <tr>
        <td><%= categorium.nome %></td>
        <td><%= link_to 'Show', categorium %></td>
        <td><%= link_to 'Edit', edit_categorium_path(categorium) %></td>
        <td><%= link_to 'Destroy', categorium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categorium', new_categorium_path %>

app/views/categoria/new.html.erb
<h1>New Categorium</h1>

<%= render 'form' %>

<%= link_to 'Back', categoria_path %>

app/views/categoria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @categorium.nome %>
</p>

<%= link_to 'Edit', edit_categorium_path(@categorium) %> |
<%= link_to 'Back', categoria_path %>

app/views/home/home.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	    <link rel="stylesheet" href="css/index.css">
	    <link rel="stylesheet" href="css/login.css">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	    <title>Upload</title>

    <title>Hello, world!</title>
  </head>
  <body>
  <%= yield %>

		<% cat = Categorium.all%>
		 
		<% todos = Video.all %>
		<% cat.each do |categoria|%>
		<div class="container" style="border-style:solid;border-width:2px">
		<h3 style="color:white"><%= categoria.nome %></h3>
		<% todos.each do |video|%>
		<% if (video.categoria == categoria.nome) %>
		<div class="card" style="width: 18rem;height:25rem;">
		 	<img class="card-img-top"> 
		 	<img src="<%= video.tumb%>" height="50%" width="100%"></img>
		 	<div class="card-body">
		    	<h6 align="center" class="card-title"><%= video.titulo%></h6>
		    	<p class="card-text"><%= video.descricao%>
		    	<p align="center">
		    	<button class="btn" align="center" onclick=<% $aula = video%>"window.location.href='/aula'">Assistir</button>
		 	</div>
		 	</div>
		</div>
		</div>

		<% end%>
		<% end%>
		<% end%>

    </div>
  </body>
</html>

app/views/login/login.html.erb
<!doctype html>
<html lang="pt-br">
	<head>
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<link rel="stylesheet" href="css/login.css">
	    <link rel="stylesheet" href="css/index.css">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	    <title>Login</title>
  	</head>
  	<body>
	<%= yield %>
	<%= form_for @user do |f| %>
            <% if @user.errors.any? %>
            <div id="error_explanation">
                        <div class="alert-error">
                                   O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
                        </div>
                        <ul>
                                   <% @user.errors.full_messages.each do |msg| %>
                                   <li><%= msg %></li>
                                   <% end %>
                        </ul>
            </div>
<% end %>
            <div class="field">
                        <%= f.label :name %>
                        <%= f.text_field :name %>
            </div>
            <div class="field">
                        <%= f.label :email %>
                        <%= f.email_field :email %>
            </div>
            <div class="field">
                        <%= f.label :password %>
                        <%= f.password_field :password %>
            </div>
            <div class="field">
                        <%= f.label :password_confirmation %>
                        <%= f.password_field :password_confirmation %>
            </div>
            <div class="actions">
                        <%= f.submit "Cadastrar"%>
            </div>
<% end %>
  		<div class="login-page">
	  		<div class="form">
			    <form class="login-form">
			    	<h2>Login</h2>
			    	<input type="text" placeholder="Username"/>
			    	<input type="password" placeholder="Password"/>
			    	<button>login</button>
			    	<div class="or-box">
			    		<span class="or">or</span>
			    	</div>
			    	<h2>Register</h2>
			    	<input type="text" placeholder="Username"/>
			    	<input type="email" placeholder="Email Address"/>
			    	<input type="password" placeholder="Password"/>
			    	<input type="password" placeholder="Confirm Password"/>			    				    	
			    	<button>Register Now</button>
			    </form>
		  	</div>
		</div>
  		


	    
	    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		<!-- Optional JavaScript -->
		<script src="script.js"></script>
  	</body>
</html>

app/views/upload/upload.html.erb
<!doctype html>
<html lang="pt-br">
	<head>
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	    <link rel="stylesheet" href="css/index.css">
	    <link rel="stylesheet" href="css/login.css">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	    <title>Upload</title>
  	</head>
  	<body>
  		<%= yield %>
  		<div class="login-page">
	  		<div class="form">
			    <form class="login-form">
			    	<h2>Upload Video</h2>
			    	<input type="text" placeholder="Título"/>
			    	<textarea name="descricao" placeholder="Descrição"></textarea>
			    	<input type="text" placeholder="Url (ex.: http://youtu.be/Hfo3s8X)"/>
			    	<input type="text" placeholder="Url da tumbnail"/>
					<select class="selectpicker show-menu-arrow" data-style="btn-primary">
					  <option>Javascript</option>
					  <option>Css</option>
					  <option>Html & Css</option>
					  <option>Ruby on Rails</option>
					  <option>Lógica de Programação</option>
					  <option>Bootstrap</option>
					</select>
			    	<button>Enviar</button>		
			    	
			    </form>
		  	</div>
		</div>
  		


	    
	    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		<!-- Optional JavaScript -->
		<script src="script.js"></script>
  	</body>
</html>

app/views/users/new.html.erb
<!doctype html>
<html lang="pt-br">
	<head>
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<link rel="stylesheet" href="css/login.css">
	    <link rel="stylesheet" href="css/index.css">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	    <title>Login</title>
  	</head>
  	<body>
	<%= yield %>
	
	  		<div class="login-page">
	  		    
	  		<div class="form">
	  		    <div class="or-box">
			    		<span class="or"></span>
			    	</div>
	  		    <h2>Register</h2>
	<%= form_for @user do |f| %>
            <% if @user.errors.any? %>
            <div id="error_explanation">
                        <div class="alert-error">
                                   O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
                        </div>
                        <ul>
                                   <% @user.errors.full_messages.each do |msg| %>
                                   <li><%= msg %></li>
                                   <% end %>
                        </ul>
            </div>
<% end %>
            <div class="field">
                        <%= f.label :name %>
                        <%= f.text_field :name %>
            </div>
            <div class="field">
                        <%= f.label :email %>
                        <%= f.email_field :email %>
            </div>
            <div class="field">
                        <%= f.label :password %>
                        <%= f.password_field :password %>
            </div>
            <div class="field">
                        <%= f.label :password_confirmation %>
                        <%= f.password_field :password_confirmation %>
            </div>
            <div class="actions">
                        <%= f.submit "Cadastrar"%>
            </div>
<% end %>
</div></div>
	    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		<!-- Optional JavaScript -->
		<script src="script.js"></script>
  	</body>
</html>