config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :categoria
    get "home" => "home#home"
    get "aula" => "aula#aula"
    get "login" => "login#login"
    get "upload" => "upload#upload"
    #root :to => "login#login"
    get 'sessions/new'
    resources :users
    get    'sign_in'   => 'sessions#new'
    post   'sign_in'   => 'sessions#create'
    delete 'sign_out'  => 'sessions#destroy'
     root 'sessions#new'
     
end

app/models/aula.rb
class Aula < ActiveRecord::Base

end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
end

app/models/login.rb
class Login < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base 
  has_secure_password
  #validates name, presence: true, length: {maximum: 50}
  #validates password, presence: true, length: {minimum: 6}
  #VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  #validates email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
  #before_save { self.email = email.downcase }
  end

app/models/video.rb
class Video < ActiveRecord::Base

end

app/controllers/aula_controller.rb
class AulaController < ApplicationController

end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  before_action :set_categorium, only: [:show, :edit, :update, :destroy]

  # GET /categoria
  # GET /categoria.json
  def index
    @categoria = Categorium.all
  end

  # GET /categoria/1
  # GET /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @categorium = Categorium.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria
  # POST /categoria.json
  def create
    @categorium = Categorium.new(categorium_params)

    respond_to do |format|
      if @categorium.save
        format.html { redirect_to @categorium, notice: 'Categorium was successfully created.' }
        format.json { render :show, status: :created, location: @categorium }
      else
        format.html { render :new }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1
  # PATCH/PUT /categoria/1.json
  def update
    respond_to do |format|
      if @categorium.update(categorium_params)
        format.html { redirect_to @categorium, notice: 'Categorium was successfully updated.' }
        format.json { render :show, status: :ok, location: @categorium }
      else
        format.html { render :edit }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1
  # DELETE /categoria/1.json
  def destroy
    @categorium.destroy
    respond_to do |format|
      format.html { redirect_to categoria_url, notice: 'Categorium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorium
      @categorium = Categorium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categorium_params
      params.require(:categorium).permit(:nome)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
before_action :block_access, except: [:destroy]
         def create  
            @user = User.find_by(email: params[:session][:email].downcase)
                        if @user && @user.authenticate(params[:session][:password])
                                   sign_in(@user)
                                   redirect_to home_path
                        else
                                   render action: :new
                        end
            end
  
              def destroy
                        sign_out
                redirect_to root_url
              end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
            @user = User.new
  end
  def create
            @user = User.new(user_params)
            if @user.save
                        redirect_to home_path, notice: "Usuário foi criado com sucesso!"
                        #tire o método de comentário quando criar o helper.
                        #Usuário depois de cadastrar-se acessa o sistema automaticamente
                        sign_in(@user)
            else 
                render action: :new
            end
  end
  private
  def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aula_helper.rb
module AulaHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
            def sign_in(a)
                        session[:user_id] = @user.id
            end
            def current_user
                        @current_user ||= User.find_by(id: session[:user_id])
            end
            def block_access
                        if current_user.present?
                                   redirect_to home_path
                        end
            end
            def logged_in?
            !current_user.nil?
            end
               def sign_out
            session.delete(:user_id)
            @current_user = nil
            end

end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
       <header class="navbar-shadow">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/home">Video Aulas</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
                <% if logged_in? %>
              
                
               
              <li>
                <p style="color:white;"><%= @current_user.name%>,
                <%= link_to "Log out", sign_out_path, method: "delete" %>
              </li>
          </li>
        <% else %>
          <li class="nav-item active">
          <%= link_to "Log in", root_path %></li>
          <ul></ul>
        	 <%= link_to "Registrar", new_user_path %>
        <% end %>
        
        
        
        
        
        

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          
<ul></ul>
            
          </ul>

          <span><a href="upload"><i class="fa fa-upload upload-icon"></i></a></span>

          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Pesquise aqui" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Procurar</button>
          </form>
        </div>
      </nav>
    </header>
    
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="js/principal.js"></script>
<%= yield %>

</body>
</html>